# Generated by Django 3.2.6 on 2022-03-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0031_alter_course_detail_student_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_detail',
            name='YT_video_url',
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='course_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='course_quiz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
