# Generated by Django 3.2.6 on 2022-03-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0032_auto_20220314_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_detail',
            name='course_title',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
