# Generated by Django 3.2.6 on 2022-03-23 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0033_alter_course_detail_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='crs_review',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
