# Generated by Django 3.2.6 on 2022-03-23 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0034_crs_review_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crs_review',
            name='date',
        ),
    ]
