# Generated by Django 3.2.6 on 2022-03-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0035_remove_crs_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='crs_review',
            name='dateby',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
