# Generated by Django 3.2.6 on 2022-02-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_page_info',
            name='about_contact',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
