# Generated by Django 3.2.6 on 2022-03-03 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0003_alter_contact_page_info_about_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_msg',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_message', to=settings.AUTH_USER_MODEL),
        ),
    ]
