# Generated by Django 3.2.6 on 2022-03-11 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20220310_2248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='review',
        ),
    ]
