# Generated by Django 3.2.6 on 2022-03-11 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_auto_20220304_1953'),
        ('blog', '0014_blog_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.student'),
        ),
    ]
