# Generated by Django 3.2.6 on 2022-03-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_blog_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_detail',
            name='blog_title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
