# Generated by Django 3.2.6 on 2022-03-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_blog_detail_blog_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_detail',
            name='imgs',
        ),
        migrations.DeleteModel(
            name='blogdetail_img',
        ),
    ]
