# Generated by Django 3.2.6 on 2022-03-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_auto_20220316_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_profile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
