# Generated by Django 3.2.6 on 2022-03-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_event_detail_event_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_detail',
            name='event_title',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
