# Generated by Django 3.2.6 on 2022-02-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220220_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses_purchase_order',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='crs_pyment'),
        ),
    ]
