# Generated by Django 3.2.6 on 2022-02-21 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_auto_20220221_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_done_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('gatewayname', models.CharField(max_length=100)),
                ('bnk_name', models.CharField(max_length=1000)),
                ('MID', models.CharField(max_length=1000)),
                ('txn_id', models.IntegerField()),
                ('order_id', models.CharField(max_length=1000)),
                ('bnk_txn_id', models.IntegerField(max_length=1000)),
                ('txn_status', models.CharField(default='pending', max_length=20)),
                ('txn_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
