# Generated by Django 3.2.6 on 2022-02-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_payment_done_detail_bnk_txn_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_done_detail',
            name='txn_time',
            field=models.DateTimeField(),
        ),
    ]
