# Generated by Django 3.2.6 on 2022-02-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_payment_done_detail_txn_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_done_detail',
            name='MID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='payment_done_detail',
            name='bnk_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='payment_done_detail',
            name='order_id',
            field=models.CharField(max_length=200),
        ),
    ]
