# Generated by Django 3.2.6 on 2022-02-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20220221_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
