# Generated by Django 3.2.6 on 2022-03-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20220303_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaytmTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDERID', models.CharField(blank=True, max_length=50)),
                ('TXNID', models.CharField(blank=True, max_length=50)),
                ('STATUS', models.CharField(blank=True, max_length=50)),
                ('TXNAMOUNT', models.CharField(blank=True, max_length=50)),
                ('CURRENCY', models.CharField(blank=True, max_length=4)),
                ('GATEWAYNAME', models.CharField(blank=True, max_length=15)),
                ('RESPMSG', models.CharField(blank=True, max_length=50)),
                ('BANKNAME', models.CharField(blank=True, max_length=50)),
                ('PAYMENTMODE', models.CharField(blank=True, max_length=50)),
                ('MID', models.CharField(blank=True, max_length=50)),
                ('RESPCODE', models.CharField(blank=True, max_length=50)),
                ('BANKTXNID', models.CharField(blank=True, max_length=50)),
                ('TXNDATE', models.DateTimeField()),
                ('CHECKSUMHASH', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='payment_done_detail',
        ),
    ]
