# Generated by Django 3.2.6 on 2022-03-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_products_purchase_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='product_title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
