# Generated by Django 3.2.6 on 2022-03-03 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login_register', '0002_frgt_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frgt_pwd',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forgot_password', to=settings.AUTH_USER_MODEL),
        ),
    ]
